[versions]
agpVersion = "8.11.1"
kotlinVersion = "2.2.0"
coreKtxVersion = "1.16.0"
lifecycleRuntimeKtxVersion = "2.9.1"
activityComposeVersion = "1.10.1"
composeBomVersion = "2025.06.01"
jetbrainsKotlinJvmVersion = "2.2.0"

[libraries]
androidxCoreKtxLibrary = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
androidxLifecycleRuntimeKtxLibrary = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidxActivityComposeLibrary = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
androidxComposeBomLibrary = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
androidxUiLibrary = { group = "androidx.compose.ui", name = "ui" }
androidxUiGraphicsLibrary = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxUiToolingLibrary = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxUiToolingPreviewLibrary = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxUiTestManifestLibrary = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidxMaterial3Library = { group = "androidx.compose.material3", name = "material3" }

[plugins]
androidApplicationPlugin = { id = "com.android.application", version.ref = "agpVersion" }
kotlinAndroidPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlinComposePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
jetbrainsKotlinJvmPlugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvmVersion" }

